import type { Product, Category, Brand, RepairOrder, Order, Notification, InstallmentPlan } from './types'

export const categories: Category[] = [
  { id: '1', slug: 'lcd', name: 'LCD و OLED', icon: '📱', color: '#1565C0', count: 342, description: 'صفحه نمایش LCD و OLED اورجینال برای انواع موبایل' },
  { id: '2', slug: 'battery', name: 'باتری', icon: '🔋', color: '#2E7D32', count: 218, description: 'باتری اورجینال و درجه یک' },
  { id: '3', slug: 'charging', name: 'شارژ و آی‌سی', icon: '⚡', color: '#F57F17', count: 156, description: 'آی‌سی شارژ، کانکتور و برد شارژ' },
  { id: '4', slug: 'camera', name: 'دوربین', icon: '📷', color: '#6A1B9A', count: 189, description: 'دوربین جلو، عقب و فلاش' },
  { id: '5', slug: 'back-glass', name: 'درب پشت', icon: '🔲', color: '#37474F', count: 124, description: 'درب پشت شیشه‌ای و فریم' },
  { id: '6', slug: 'face-id', name: 'Face ID', icon: '🔐', color: '#C62828', count: 87, description: 'قطعات Face ID و سنسور چهره' },
  { id: '7', slug: 'speaker', name: 'اسپیکر و میکروفون', icon: '🔊', color: '#00695C', count: 145, description: 'اسپیکر صدا، ایرپیس و میکروفون' },
  { id: '8', slug: 'flex', name: 'فلت و کابل', icon: '🔗', color: '#1565C0', count: 276, description: 'انواع فلت و کابل رابط' },
  { id: '9', slug: 'tools', name: 'ابزار تعمیر', icon: '🔧', color: '#4E342E', count: 198, description: 'پیچ‌گوشتی، پنس، قلم لحیم و ابزار تعمیر' },
  { id: '10', slug: 'equipment', name: 'دستگاه تعمیر', icon: '🔬', color: '#283593', count: 67, description: 'میکروسکوپ، هات‌ایر، استیشن لحیم' },
  { id: '11', slug: 'motherboard', name: 'مادربرد و آی‌سی', icon: '🖥️', color: '#880E4F', count: 312, description: 'انواع آی‌سی، CPU و چیپ‌ست' },
  { id: '12', slug: 'accessories', name: 'لوازم جانبی', icon: '🎧', color: '#0277BD', count: 425, description: 'لوازم جانبی و محافظ گوشی' },
]

export const brands: Brand[] = [
  { id: '1', name: 'Apple', logo: '/brands/apple.svg', productCount: 456 },
  { id: '2', name: 'Samsung', logo: '/brands/samsung.svg', productCount: 389 },
  { id: '3', name: 'Xiaomi', logo: '/brands/xiaomi.svg', productCount: 234 },
  { id: '4', name: 'Huawei', logo: '/brands/huawei.svg', productCount: 178 },
  { id: '5', name: 'OnePlus', logo: '/brands/oneplus.svg', productCount: 145 },
  { id: '6', name: 'Oppo', logo: '/brands/oppo.svg', productCount: 198 },
]

export const products: Product[] = [
  {
    id: '1',
    slug: 'iphone-14-pro-lcd-oled',
    name: 'صفحه نمایش OLED آیفون ۱۴ پرو',
    nameEn: 'iPhone 14 Pro OLED Screen',
    brand: 'Apple',
    model: 'iPhone 14 Pro',
    category: 'LCD و OLED',
    categorySlug: 'lcd',
    price: 8500000,
    originalPrice: 9800000,
    installmentPrice: 8800000,
    monthlyPayment: 733333,
    downPayment: 2000000,
    installmentMonths: 12,
    images: ['/products/iphone14pro-lcd.png', '/products/iphone14pro-lcd.png'],
    thumbnail: '/products/iphone14pro-lcd.png',
    rating: 4.8,
    reviewCount: 124,
    stock: 23,
    sold: 342,
    isNew: false,
    isFeatured: true,
    isBestSeller: true,
    hasInstallment: true,
    discount: 13,
    description: 'صفحه نمایش OLED اورجینال آیفون ۱۴ پرو با رزولوشن ۲۵۵۶×۱۱۷۹ و نرخ نوسازی ۱۲۰ هرتز. این صفحه با کیفیت اورجینال اپل بوده و به همراه تاچ فریم ارائه می‌شود.',
    specifications: {
      'نوع': 'OLED',
      'رزولوشن': '۲۵۵۶×۱۱۷۹',
      'اندازه': '۶.۱ اینچ',
      'نرخ نوسازی': '۱۲۰ هرتز',
      'کیفیت': 'اورجینال',
    },
    tags: ['آیفون', 'اپل', 'OLED', 'صفحه نمایش'],
    warranty: '۶ ماه ضمانت',
    sku: 'APL-14P-LCD-001',
    badge: 'sale',
  },
  {
    id: '2',
    slug: 'samsung-s23-ultra-lcd',
    name: 'صفحه نمایش Dynamic AMOLED سامسونگ S23 Ultra',
    nameEn: 'Samsung S23 Ultra Dynamic AMOLED',
    brand: 'Samsung',
    model: 'Galaxy S23 Ultra',
    category: 'LCD و OLED',
    categorySlug: 'lcd',
    price: 6200000,
    originalPrice: 6200000,
    installmentPrice: 6500000,
    monthlyPayment: 541667,
    downPayment: 1500000,
    installmentMonths: 12,
    images: ['/products/s23ultra-lcd.png'],
    thumbnail: '/products/s23ultra-lcd.png',
    rating: 4.7,
    reviewCount: 89,
    stock: 15,
    sold: 218,
    isFeatured: true,
    hasInstallment: true,
    description: 'صفحه نمایش Dynamic AMOLED 2X سامسونگ گلکسی S23 Ultra',
    specifications: {
      'نوع': 'Dynamic AMOLED 2X',
      'رزولوشن': '۳۰۸۸×۱۴۴۰',
      'اندازه': '۶.۸ اینچ',
    },
    tags: ['سامسونگ', 'AMOLED', 'S23 Ultra'],
    warranty: '۶ ماه ضمانت',
    sku: 'SAM-S23U-LCD-001',
    badge: 'bestseller',
  },
  {
    id: '3',
    slug: 'iphone-15-battery',
    name: 'باتری آیفون ۱۵',
    nameEn: 'iPhone 15 Battery',
    brand: 'Apple',
    model: 'iPhone 15',
    category: 'باتری',
    categorySlug: 'battery',
    price: 1250000,
    originalPrice: 1500000,
    installmentPrice: 1300000,
    monthlyPayment: 108333,
    downPayment: 400000,
    installmentMonths: 12,
    images: ['/products/iphone15-bat.png'],
    thumbnail: '/products/iphone15-bat.png',
    rating: 4.9,
    reviewCount: 267,
    stock: 87,
    sold: 1243,
    isBestSeller: true,
    hasInstallment: true,
    discount: 17,
    description: 'باتری اورجینال آیفون ۱۵ با ظرفیت ۳۸۷۷ میلی‌آمپر ساعت',
    specifications: {
      'ظرفیت': '۳۸۷۷ mAh',
      'ولتاژ': '۳.۸۸ ولت',
      'کیفیت': 'اورجینال',
    },
    tags: ['باتری', 'آیفون', 'اپل'],
    warranty: '۳ ماه ضمانت',
    sku: 'APL-15-BAT-001',
    badge: 'sale',
  },
  {
    id: '4',
    slug: 'xiaomi-13-ultra-lcd',
    name: 'صفحه نمایش شیائومی ۱۳ Ultra',
    nameEn: 'Xiaomi 13 Ultra Display',
    brand: 'Xiaomi',
    model: '13 Ultra',
    category: 'LCD و OLED',
    categorySlug: 'lcd',
    price: 4800000,
    originalPrice: 4800000,
    images: ['/products/xiaomi13u-lcd.png'],
    thumbnail: '/products/xiaomi13u-lcd.png',
    rating: 4.6,
    reviewCount: 45,
    stock: 8,
    sold: 134,
    isNew: true,
    hasInstallment: false,
    description: 'صفحه نمایش AMOLED شیائومی ۱۳ Ultra',
    specifications: {
      'نوع': 'AMOLED',
      'رزولوشن': '۳۲۰۰×۱۴۴۰',
    },
    tags: ['شیائومی', 'AMOLED'],
    warranty: '۶ ماه ضمانت',
    sku: 'XIA-13U-LCD-001',
    badge: 'new',
  },
  {
    id: '5',
    slug: 'iphone-13-face-id',
    name: 'فیس آی‌دی آیفون ۱۳',
    nameEn: 'iPhone 13 Face ID Module',
    brand: 'Apple',
    model: 'iPhone 13',
    category: 'Face ID',
    categorySlug: 'face-id',
    price: 3200000,
    originalPrice: 3800000,
    images: ['/products/iphone13-faceid.png'],
    thumbnail: '/products/iphone13-faceid.png',
    rating: 4.7,
    reviewCount: 78,
    stock: 12,
    sold: 289,
    isFeatured: true,
    hasInstallment: true,
    discount: 16,
    description: 'ماژول فیس آی‌دی اورجینال آیفون ۱۳',
    specifications: {
      'کیفیت': 'اورجینال',
      'سازگاری': 'آیفون ۱۳ / ۱۳ Mini',
    },
    tags: ['فیس آی‌دی', 'آیفون', 'اپل'],
    warranty: '۳ ماه ضمانت',
    sku: 'APL-13-FID-001',
    badge: 'sale',
  },
  {
    id: '6',
    slug: 'soldering-station-pro',
    name: 'استیشن لحیم JBC CD-2BB حرفه‌ای',
    nameEn: 'JBC CD-2BB Professional Soldering Station',
    brand: 'JBC',
    model: 'CD-2BB',
    category: 'دستگاه تعمیر',
    categorySlug: 'equipment',
    price: 12500000,
    originalPrice: 14000000,
    installmentPrice: 13000000,
    monthlyPayment: 1083333,
    downPayment: 3000000,
    installmentMonths: 12,
    images: ['/products/jbc-cd2bb.png'],
    thumbnail: '/products/jbc-cd2bb.png',
    rating: 4.9,
    reviewCount: 156,
    stock: 5,
    sold: 87,
    isFeatured: true,
    hasInstallment: true,
    discount: 11,
    description: 'استیشن لحیم حرفه‌ای JBC با دقت بالا برای تعمیرات SMD',
    specifications: {
      'توان': '۱۵۰ وات',
      'دمای کار': '۱۵۰ تا ۴۵۰ درجه',
      'دقت': '±۲ درجه',
    },
    tags: ['استیشن لحیم', 'ابزار تعمیر', 'JBC'],
    warranty: '۱ سال ضمانت',
    sku: 'JBC-CD2BB-001',
    badge: 'sale',
  },
  {
    id: '7',
    slug: 'samsung-a54-battery',
    name: 'باتری سامسونگ A54',
    nameEn: 'Samsung A54 Battery',
    brand: 'Samsung',
    model: 'Galaxy A54',
    category: 'باتری',
    categorySlug: 'battery',
    price: 890000,
    originalPrice: 890000,
    images: ['/products/sama54-bat.png'],
    thumbnail: '/products/sama54-bat.png',
    rating: 4.5,
    reviewCount: 198,
    stock: 45,
    sold: 876,
    isBestSeller: true,
    hasInstallment: false,
    description: 'باتری اورجینال سامسونگ گلکسی A54 با ظرفیت ۵۰۰۰ میلی‌آمپر',
    specifications: {
      'ظرفیت': '۵۰۰۰ mAh',
      'ولتاژ': '۳.۸۸ ولت',
    },
    tags: ['باتری', 'سامسونگ', 'A54'],
    warranty: '۳ ماه ضمانت',
    sku: 'SAM-A54-BAT-001',
    badge: 'bestseller',
  },
  {
    id: '8',
    slug: 'microscope-trinocular',
    name: 'میکروسکوپ تثلیثی ۷-۴۵X با لنز باریلو',
    nameEn: 'Trinocular Microscope 7-45X Barlow Lens',
    brand: 'AmScope',
    model: 'SM-4TZ-144A',
    category: 'دستگاه تعمیر',
    categorySlug: 'equipment',
    price: 18500000,
    originalPrice: 22000000,
    installmentPrice: 19500000,
    monthlyPayment: 1625000,
    downPayment: 5000000,
    installmentMonths: 12,
    images: ['/products/microscope.png'],
    thumbnail: '/products/microscope.png',
    rating: 4.8,
    reviewCount: 67,
    stock: 3,
    sold: 45,
    isFeatured: true,
    hasInstallment: true,
    discount: 16,
    description: 'میکروسکوپ حرفه‌ای تثلیثی برای تعمیرات برد مادر',
    specifications: {
      'بزرگنمایی': '۷-۴۵X',
      'نوع': 'تثلیثی',
      'روشنایی': '۱۴۴ LED',
    },
    tags: ['میکروسکوپ', 'ابزار تعمیر'],
    warranty: '۱ سال ضمانت',
    sku: 'AMS-M45-001',
    badge: 'sale',
  },
]

export const featuredProducts = products.filter(p => p.isFeatured)
export const bestSellers = products.filter(p => p.isBestSeller)
export const newProducts = products.filter(p => p.isNew)

export const mockOrders: Order[] = [
  {
    id: '1',
    orderNumber: 'PAD-1234567',
    date: '۱۴۰۳/۰۴/۱۵',
    status: 'delivered',
    items: [{ product: products[0], quantity: 1 }],
    total: 8500000,
    paymentMethod: 'online',
    address: {
      id: '1',
      title: 'منزل',
      fullName: ' فراز بدرقه',
      phone: '09361577733',
      province: 'ارومیه',
      city: 'ارومیه',
      street: 'فلکه خیام رو به روی بانک پاسارگاد',
      postalCode: '1234567890',
      isDefault: true,
    },
    trackingCode: 'IR12345678901',
  },
  {
    id: '2',
    orderNumber: 'PAD-1234568',
    date: '۱۴۰۳/۰۴/۲۰',
    status: 'processing',
    items: [{ product: products[2], quantity: 2 }],
    total: 2500000,
    paymentMethod: 'installment',
    address: {
      id: '1',
      title: 'منزل',
      fullName: 'علی محمدی',
      phone: '09120000000',
      province: 'تهران',
      city: 'تهران',
      street: 'خیابان ولیعصر، پلاک ۱۲',
      postalCode: '1234567890',
      isDefault: true,
    },
  },
]

export const mockRepairOrders: RepairOrder[] = [
  {
    id: '1',
    ticketNumber: 'REP-78901',
    deviceBrand: 'Apple',
    deviceModel: 'iPhone 14 Pro',
    problem: 'صفحه شکسته و تاچ کار نمی‌کند',
    status: 'in-progress',
    estimatedCost: 3500000,
    createdAt: '۱۴۰۳/۰۴/۱۰',
    updatedAt: '۱۴۰۳/۰۴/۱۵',
    technicianName: 'محمد رضایی',
    warranty: '۳ ماه',
    timeline: [
      { id: '1', status: 'دریافت دستگاه', note: 'دستگاه تحویل گرفته شد', timestamp: '۱۴۰۳/۰۴/۱۰ ۱۴:۳۰' },
      { id: '2', status: 'بررسی اولیه', note: 'تشخیص داده شد: شکستگی LCD و تاچ', timestamp: '۱۴۰۳/۰۴/۱۱ ۱۰:۱۵' },
      { id: '3', status: 'در حال تعمیر', note: 'تعمیر آغاز شد - قطعه جدید نصب در حال انجام', timestamp: '۱۴۰۳/۰۴/۱۵ ۰۹:۰۰' },
    ],
  },
]

export const mockNotifications: Notification[] = [
  { id: '1', title: 'سفارش شما ارسال شد', message: 'سفارش PAD-1234567 از انبار خارج شد. کد رهگیری: IR12345678901', type: 'order', read: false, date: '۱۴۰۳/۰۴/۲۱' },
  { id: '2', title: 'تخفیف ویژه!', message: 'تخفیف ۳۰٪ برای صفحه‌نمایش‌های آیفون فقط تا پایان امروز', type: 'promotion', read: false, date: '۱۴۰۳/۰۴/۲۰' },
  { id: '3', title: 'وضعیت تعمیر به‌روز شد', message: 'تعمیر گوشی شما در حال انجام است. REP-78901', type: 'repair', read: true, date: '۱۴۰۳/۰۴/۱۵' },
]

export const installmentPlans: InstallmentPlan[] = [
  { months: 3, interestRate: 2, minDownPayment: 30 },
  { months: 6, interestRate: 5, minDownPayment: 25 },
  { months: 12, interestRate: 10, minDownPayment: 20 },
  { months: 18, interestRate: 15, minDownPayment: 20 },
  { months: 24, interestRate: 20, minDownPayment: 25 },
]

export function formatPrice(price: number): string {
  return new Intl.NumberFormat('fa-IR').format(price) + ' تومان'
}

export function calculateInstallment(
  price: number,
  months: number,
  downPaymentPercent: number,
  interestRate: number
) {
  const downPayment = Math.ceil(price * (downPaymentPercent / 100))
  const remaining = price - downPayment
  const totalWithInterest = remaining * (1 + interestRate / 100)
  const monthlyPayment = Math.ceil(totalWithInterest / months)
  return { downPayment, monthlyPayment, total: downPayment + totalWithInterest }
}
